
echo "NumTables=1"
gnuplot -e "tables=1" gnuplot_length
echo "NumTables=2"
gnuplot -e "tables=2" gnuplot_length
echo "NumTables=4"
gnuplot -e "tables=4" gnuplot_length
echo "NumTables=8"
gnuplot -e "tables=8" gnuplot_length
echo "NumTables=16"
gnuplot -e "tables=16" gnuplot_length
echo "NumTables=31"
gnuplot -e "tables=31" gnuplot_length
echo "NumTables=32"
gnuplot -e "tables=32" gnuplot_length
echo "NumTables=33"
gnuplot -e "tables=33" gnuplot_length
echo "NumTables=64"
gnuplot -e "tables=64" gnuplot_length
